### ISSUE TITLE
internal Error in contao 4.4.8

### ISSUE THREAD

**Issue by kgansberger** [Kuestenschmiede/ExportBundle#1]
Hallo!

bekomme folgende "Internal Errors":

Export:
Attempted to load class "GetEventHelper" from namespace "esit\con4gis\ExportBundle\Classes\Helper". Did you forget a "use" statement for "con4gis\ExportBundle\Classes\Helper\GetEventHelper"?

Info & help:
Attempted to load class "C4GHTMLFactory" from namespace "con4gis\MapsBundle\Resources\contao\classes". Did you forget a "use" statement for "con4gis\CoreBundle\Resources\contao\classes\C4GHTMLFactory"?

Hat die Schmiede einen Tipp für mich?

**Comment by coastforge-mei** [comment]
Hallo kgangsberger,

danke für Dein Feedback. Wir werden schnellstmöglich neue Versionen erstellen. Da haben sich bei der "Bundle-Umstellung" leider zwei ... Fehler eingeschlichen.
